version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    env_file:
      - .env

  # celery:
  #   build: .
  #   command: celery -A backend worker -l info
  #   volumes:
  #     - .:/code
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis

  # celery-beat:
  #   build: .
  #   command: celery -A backend beat -l info
  #   volumes:
  #     - .:/code
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #     - web

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  caddy_data:
  caddy_config:
