version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:9500
    volumes:
      - .:/app
    ports:
      - "9500:9500"
    environment:
      - DEBUG=1  # Set to 0 for production
    # depends_on:
    #   - db

  # db:
  #   image: postgres:14
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_DB=mydb
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword

# volumes:
#   postgres_data:
